### PR TITLE
Done with Algos

### PR DESCRIPTION
**Pull request by Coder1221**

### CODE REVIEW

**Comment by Moiz1524** [comment]
Please complete implementation for missing month groups!

**Review by thejunaidiqbal1 — COMMENTED** [review]
Date time with zones, problem 1 issue on output

**Review by Moiz1524 — CHANGES_REQUESTED** [review]
Add 140 characters check inside hashtag problem. Learn types of Ruby exceptions and use *raise SomeError* as needed.

**Review by thejunaidiqbal1 — COMMENTED** [review]
Implemented all the changes

**Pull request merged**
